# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: FastApi CD

on:
  workflow_run: 
    workflows: ["FastApi CI"]
    type: 
      - completed

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Check Docker installation
      run: docker --version

    - name: Pull docker images from dockerhub
      run: docker pull fabien123/ci-cd-fastapi:latest

    - name: Delete Old docker container
      run: docker rm -f ci-cd-fastapi || true
      
    - name: Run Docker Container
      run: docker run -d -p 8080:8080 --name ci-cd-fastapi fabien123/ci-cd-fastapi

    
